title: "IoT School Development Kit: Documentation"
description: "Complete guide for Lorfi projects and applications"
baseurl: "/iotlauncher"
url: "https://iotlauncher.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - docs/Software_Guide.md
  - docs/Hardware_Guide.md
  - docs/Components_Lists.md

include:
  - docs

# Collections for better organization
collections:
  projects:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
